### ISSUE TITLE
使用 &jm 但 沒有出現 訊息內容 → 設定加入訊息

### ISSUE THREAD

**Issue by Siaomo** [yeecord/website#120]
![image](https://user-images.githubusercontent.com/78332860/220500800-1a91af62-5169-4bc7-9a5a-7e1560ac8a59.png)
![image](https://user-images.githubusercontent.com/78332860/220500827-c4d1a699-b156-4dd3-aeeb-690e22f50c5f.png)
我打了&jm 但沒顯示選項是我設定哪邊環節沒用好權限嗎

**Comment by Gary50613** [comment]
@Siaomo 指令使用上的問題可以到我們 [支援群組](https://discord.gg/yeecord) 詢問哦
