### ISSUE TITLE
Feedback for “如何使用私人頻道解決伺服器大小事”

### ISSUE THREAD

**Issue by henrylee2006** [yeecord/website#138]
頻道使用時無法關閉，刪除後再用就出現以下畫面

![螢幕擷取畫面 2023-04-06 045242](https://user-images.githubusercontent.com/114851650/230209777-739034db-419a-4ee6-b8db-a71f2d2cd71b.png)

**Comment by SonMooSans** [comment]
You need to close the private channel by clicking the button. Forcely deleting it may cause unexpected behaviors.

Enable "允許使用者關閉" to allow users to close the channel themselves, for further questions, please refer to the Discord community for help.
