### ISSUE TITLE
hello，我需要詢問一個相關問題

### ISSUE THREAD

**Issue by wfq1971** [yeecord/website#281]
你好，我之前使用機器龍的音樂來源沒有包括spotify，之後按照你的建議使用了JMusicBot，但是它去播放youtube會播放不了，請問如何才能使用機器龍來播放流行音樂（不是二次創作的soundcloud來源）

**Comment by kane50613** [comment]
就是因為 YouTube 會一直擋所以大家都播不了哦 🥲
